### ISSUE TITLE
RandomThings Spectre Anchor NBT tag support

### ISSUE THREAD

**Issue by ubergarm** [QuantumlyTangled/DeathChests#6]
I've been enjoying Grave Keeper and would like to add it to my modpack [Sky Magic Islands](https://www.curseforge.com/minecraft/modpacks/sky-magic-islands), however, I can't yet get it to work with RandomThings Spectre Anchors.

Spectre Anchors work much like Botania's Resolute Ivy, however they are set to `0 as byte` instead of `true` or `1 as byte` as seen in this example where I applied both to a diamond sword:
```
<minecraft:diamond_sword>.withTag({Botania_keepIvy: 1 as byte, spectreAnchor: 0 as byte})
```

Would it be possible to change the config to just check if the key is present in the NBTs, and ignore the value? e.g.

```
    # List of NBT boolean that are considered as soulbinding when set to ~true~ -> ANYTHING
     S:soulbound_tag_boolean <
         Botania_keepIvy
         spectreAnchor
      >
```

Thanks much and have a good one!

**Comment by ubergarm** [comment]
I did a little more testing, apparently its not quite as simple as checking if the key appears, as the botania resolute ivy will keep the key but set the value to `0` after a single death... Whereas the spectre anchor has 'unlimited uses'...

This is the code in question:
https://github.com/Modqly/GraveKeeper/blob/94b1d486c57562dcbc91697640804dac6b651b5b/src/main/java/com/quantumlytangled/gravekeeper/util/SoulboundHandler.java#L30

I don't know an easy way offhand to support more possible NBTs, other than perhaps adding the desired value or a wildcard to the config e.g.:
```
    # List of NBT boolean that are considered as soulbinding when set specified value or * for wildcard
     S:soulbound_tag_boolean <
         Botania_keepIvy:1
         spectreAnchor:0
         someOtherMod:*
      >
```

Anyway, just some thoughts!

Cheers and thanks again!

**Comment by LemADEC** [comment]
To be fair, I'm half tempted to support it just to clear the tag and fix it's unbalance.

**Comment by Quantumlyy** [comment]
> To be fair, I'm half tempted to support it just to clear the tag and fix it's unbalance.

Is it really that bad?
Though them writing a 0 byte tag as an indicator of presence is quite unorthodox.
